## School Census of the Peruvian Republic of 1902

![map](http://3.bp.blogspot.com/-3qppyxTSvAQ/UTEak3Tn5xI/AAAAAAAAAJQ/9imqDUmNcG4/s1600/EL+PERU+Y+SUS+FRONTERAS+ANTIGUAS+-+colores.png)

In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame

## Data I/O

The pandas library has functions that make importing and exporting data simple. The functions allow for a variety of file formats to be imported and exported, including CSV, Excel, HDF5, SQL, JSON, HTML, and pickle files.

|Method|Description|
|------|-----------|
|read_excel( )|Read a excel and convert to a excel file|
|to_csv( )| Write the index and entries to a CSV file|
|read_csv( )| Read a csv and convert into a DataFrame|
|to_json( )| Convert the object to a JSON string|
|to_pickle( )| Serialize the object and store it in an external file|
|to_sql( )| Write the object data to an open SQL database|
|read_html( )| Read a table in an html page and convert to a DataFrame|

In [7]:
# REGION JUNIN
junin_data = pd.read_excel(r"C:\Users\ASUS\Downloads\Region_Junin.xlsx",) #"r" - Read - Default value. Opens a file for reading
junin_data

,Unnamed: 0,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,...,209,544,361,216,1,1,4,284,290,1
1,1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,...,50,100,50,50,0,0,0,100,0,0
2,2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,...,25,72,47,25,0,0,0,69,3,0
3,3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,...,25,50,25,25,0,0,0,25,25,0
4,4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,...,25,50,25,25,0,0,0,37,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,...,0,72,72,0,0,0,0,35,39,0
193,193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,...,7,23,16,7,0,0,0,21,2,0
194,194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,...,8,30,22,8,0,0,0,4,26,0
195,195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,...,37,103,76,44,0,0,37,14,69,0
196,196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,...,30,126,96,30,0,0,1,118,7,0

In [8]:
junin_data.columns

Index(['Unnamed: 0', 'Region', 'District', 'Place', '4_6_years_men',
       '4_6_years_women', '4_6_years_total', '6_14_years_men',
       '6_14_years_women', '6_14_years_total', 'man_read', 'women_read',
       'total_read', 'men_not_read', 'women_not_read', 'total_not_read',
       'man_write', 'women_write', 'total_write', 'men_not_write',
       'women_not_write', 'total_not_write', 'instruction_men',
       'instruction_women', 'instruction_total', 'no_instruction_men',
       'no_instruction_women', 'no_instruction_total', 'finished_instr_men',
       'finished_instr_women', 'finished_instr_total',
       'not_finished_instr_men', 'not_finished_instr_women',
       'not_finished_instr_total', 'peruvian_men', 'peruvian_women',
       'foreign_men', 'foreign_women', 'whites', 'natives', 'mestizos',
       'blacks'],
      dtype='object')

In [9]:
junin = junin_data.drop(columns = 'Unnamed: 0')
junin

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,209,544,361,216,1,1,4,284,290,1
1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,30,...,50,100,50,50,0,0,0,100,0,0
2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,25,...,25,72,47,25,0,0,0,69,3,0
3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,25,...,25,50,25,25,0,0,0,25,25,0
4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,3,...,25,50,25,25,0,0,0,37,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,42,...,0,72,72,0,0,0,0,35,39,0
193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,8,...,7,23,16,7,0,0,0,21,2,0
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,7,...,8,30,22,8,0,0,0,4,26,0
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,41,...,37,103,76,44,0,0,37,14,69,0
196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,8,...,30,126,96,30,0,0,1,118,7,0

In [12]:
junin.to_excel('junin.xlsx')

In [13]:
# info() 
junin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Region                    197 non-null    object
 1   District                  197 non-null    object
 2   Place                     197 non-null    object
 3   4_6_years_men             197 non-null    int64
 4   4_6_years_women           197 non-null    int64
 5   4_6_years_total           197 non-null    int64
 6   6_14_years_men            197 non-null    int64
 7   6_14_years_women          197 non-null    int64
 8   6_14_years_total          197 non-null    int64
 9   man_read                  197 non-null    int64
 10  women_read                197 non-null    int64
 11  total_read                197 non-null    int64
 12  men_not_read              197 non-null    int64
 13  women_not_read            197 non-null    int64
 14  total_not_read            197 non-null    int64
 15  man_write                 197 non-null    int64
 16  women_write               197 non-null    int64
 17  total_write               197 non-null    int64
 18  men_not_write             197 non-null    int64
 19  women_not_write           197 non-null    int64
 20  total_not_write           197 non-null    int64
 21  instruction_men           197 non-null    int64
 22  instruction_women         197 non-null    int64
 23  instruction_total         197 non-null    int64
 24  no_instruction_men        197 non-null    int64
 25  no_instruction_women      197 non-null    int64
 26  no_instruction_total      197 non-null    int64
 27  finished_instr_men        197 non-null    int64
 28  finished_instr_women      197 non-null    int64
 29  finished_instr_total      197 non-null    int64
 30  not_finished_instr_men    197 non-null    int64
 31  not_finished_instr_women  197 non-null    int64
 32  not_finished_instr_total  197 non-null    int64
 33  peruvian_men              197 non-null    int64
 34  peruvian_women            197 non-null    int64
 35  foreign_men               197 non-null    int64
 36  foreign_women             197 non-null    int64
 37  whites                    197 non-null    int64
 38  natives                   197 non-null    int64
 39  mestizos                  197 non-null    int64
 40  blacks                    197 non-null    int64
dtypes: int64(38), object(3)
memory usage: 63.2+ KB

In [15]:
# isnull().values.any() 
junin['Place'].isnull().values.any()

False

In [16]:
# shape
junin.shape

(197, 41)

In [17]:
# describe()
junin.describe()

,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,women_read,total_read,men_not_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
count,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,...,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000
mean,16.979695,15.345178,32.324873,79.005076,62.482234,141.538071,34.654822,11.705584,46.360406,61.294416,...,79.238579,172.675127,95.918782,77.664975,0.030457,0.010152,9.893401,110.558376,52.583756,0.776650
std,22.571419,21.618979,43.489455,99.837291,90.879972,188.535210,51.091581,34.676708,83.291516,84.511046,...,111.799104,220.657751,120.177520,110.539722,0.265511,0.100501,39.677190,131.094774,123.120065,7.584952
min,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,4.000000,8.000000,25.000000,19.000000,42.000000,2.000000,0.000000,2.000000,22.000000,...,25.000000,50.000000,31.000000,25.000000,0.000000,0.000000,0.000000,40.000000,0.000000,0.000000
50%,10.000000,9.000000,20.000000,55.000000,41.000000,91.000000,21.000000,0.000000,23.000000,41.000000,...,50.000000,108.000000,65.000000,50.000000,0.000000,0.000000,0.000000,73.000000,3.000000,0.000000
75%,20.000000,18.000000,39.000000,88.000000,73.000000,160.000000,42.000000,7.000000,50.000000,65.000000,...,94.000000,197.000000,103.000000,91.000000,0.000000,0.000000,0.000000,143.000000,48.000000,0.000000
max,184.000000,184.000000,368.000000,950.000000,957.000000,1907.000000,317.000000,225.000000,542.000000,817.000000,...,1089.000000,2164.000000,1132.000000,1141.000000,3.000000,1.000000,348.000000,1367.000000,808.000000,92.000000

In [18]:
# values
junin.values

array([['JUNIN', 'CIUDAD DEL CERRO', 'C.CIUDAD DEL CERRO', ..., 284, 290,
        1],
       ['JUNIN', 'CIUDAD DEL CERRO', 'P.YANACANCHA', ..., 100, 0, 0],
       ['JUNIN', 'CIUDAD DEL CERRO', 'VICO', ..., 69, 3, 0],
       ...,
       ['JUNIN', 'YAULI', 'PACHACHACA', ..., 4, 26, 0],
       ['JUNIN', 'YAULI', 'YAULI', ..., 14, 69, 0],
       ['JUNIN', 'YAULI', 'MINAS DE MOROCOCHA', ..., 118, 7, 0]],
      dtype=object)

In [19]:
# index
junin.index

RangeIndex(start=0, stop=197, step=1)

In [23]:
junin.head()

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,209,544,361,216,1,1,4,284,290,1
1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,30,...,50,100,50,50,0,0,0,100,0,0
2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,25,...,25,72,47,25,0,0,0,69,3,0
3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,25,...,25,50,25,25,0,0,0,25,25,0
4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,3,...,25,50,25,25,0,0,0,37,13,0

In [24]:
junin.dtypes

Region                      object
District                    object
Place                       object
4_6_years_men                int64
4_6_years_women              int64
4_6_years_total              int64
6_14_years_men               int64
6_14_years_women             int64
6_14_years_total             int64
man_read                     int64
women_read                   int64
total_read                   int64
men_not_read                 int64
women_not_read               int64
total_not_read               int64
man_write                    int64
women_write                  int64
total_write                  int64
men_not_write                int64
women_not_write              int64
total_not_write              int64
instruction_men              int64
instruction_women            int64
instruction_total            int64
no_instruction_men           int64
no_instruction_women         int64
no_instruction_total         int64
finished_instr_men           int64
finished_instr_women         int64
finished_instr_total         int64
not_finished_instr_men       int64
not_finished_instr_women     int64
not_finished_instr_total     int64
peruvian_men                 int64
peruvian_women               int64
foreign_men                  int64
foreign_women                int64
whites                       int64
natives                      int64
mestizos                     int64
blacks                       int64
dtype: object

In [25]:
junin.nunique()

Region                        1
District                     35
Place                       193
4_6_years_men                54
4_6_years_women              54
4_6_years_total              75
6_14_years_men              112
6_14_years_women            101
6_14_years_total            130
man_read                     78
women_read                   42
total_read                   81
men_not_read                 99
women_not_read               99
total_not_read              123
man_write                    67
women_write                  32
total_write                  67
men_not_write               104
women_not_write             103
total_not_write             133
instruction_men              73
instruction_women            31
instruction_total            81
no_instruction_men           98
no_instruction_women        105
no_instruction_total        130
finished_instr_men           20
finished_instr_women         12
finished_instr_total         22
not_finished_instr_men      112
not_finished_instr_women    105
not_finished_instr_total    132
peruvian_men                110
peruvian_women              102
foreign_men                   4
foreign_women                 2
whites                       32
natives                     128
mestizos                     78
blacks                        6
dtype: int64

In [26]:
junin_pop = junin[['4_6_years_total','6_14_years_total']]
junin_pop

     4_6_years_total  6_14_years_total
0                111               468
1                  4                96
2                  1                71
3                  6                44
4                  8                42
..               ...               ...
192                1                71
193                1                22
194                2                28
195                8               112
196               14               112

[197 rows x 2 columns]

In [27]:
junin_pop.sum()

4_6_years_total      6368
6_14_years_total    27883
dtype: int64

In [28]:
junin_cdc = junin.loc[junin['District'] == 'CIUDAD DEL CERRO']
junin_cdc

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,209,544,361,216,1,1,4,284,290,1
1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,30,...,50,100,50,50,0,0,0,100,0,0
2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,25,...,25,72,47,25,0,0,0,69,3,0
3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,25,...,25,50,25,25,0,0,0,25,25,0
4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,3,...,25,50,25,25,0,0,0,37,13,0
5,JUNIN,CIUDAD DEL CERRO,QUIRLACOCHA,6,7,13,44,43,87,13,...,50,100,50,50,0,0,0,65,35,0
6,JUNIN,CIUDAD DEL CERRO,CAJAMARQUILLA,9,8,17,31,39,70,0,...,47,87,40,47,0,0,0,87,0,0
7,JUNIN,CIUDAD DEL CERRO,CAICO,18,23,41,90,77,167,34,...,99,206,108,100,0,0,4,175,29,0
8,JUNIN,CIUDAD DEL CERRO,ROCO,7,4,11,42,19,61,0,...,23,72,49,23,0,0,0,70,2,0
9,JUNIN,CIUDAD DEL CERRO,C.SACRA FAMILIA,16,8,24,26,25,51,1,...,33,75,42,33,0,0,0,73,2,0
10,JUNIN,CIUDAD DEL CERRO,P.QUINUA,8,6,14,17,19,36,0,...,25,50,25,25,0,0,0,50,0,0
11,JUNIN,CIUDAD DEL CERRO,H.PARIAHUANCA,2,6,8,10,12,22,0,...,18,30,12,18,0,0,0,24,6,0
12,JUNIN,CIUDAD DEL CERRO,P.SULLUMARCA,12,14,26,38,32,70,0,...,46,96,50,46,0,0,0,96,0,0
13,JUNIN,CIUDAD DEL CERRO,H.SAN ANDRÉS,8,0,8,17,25,42,3,...,25,50,25,25,0,0,0,44,6,0

In [29]:
junin_50 = junin[junin['4_6_years_total'] > 50]
junin_50

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,209,544,361,216,1,1,4,284,290,1
28,JUNIN,CAYNA,PÁUCAR,26,31,57,66,44,110,18,...,75,147,72,0,0,0,0,119,28,0
47,JUNIN,JAUJA,P.JAUJA,69,71,140,375,327,702,265,...,374,749,444,398,0,0,63,117,662,0
51,JUNIN,JAUJA,A.HUERTAS,22,38,60,103,87,190,84,...,125,246,125,125,0,0,0,195,55,0
57,JUNIN,JAUJA,P.RICRÁN,36,21,57,98,93,191,42,...,114,248,134,114,0,0,0,240,8,0
59,JUNIN,APATA,P.APATA,133,82,215,487,218,705,85,...,299,908,620,300,0,0,2,264,654,0
62,JUNIN,APATA,PACUCHO,29,22,51,117,113,230,50,...,135,280,146,135,0,0,0,34,247,0
63,JUNIN,ORCOTUNA,P.ORCOTUNA,47,60,107,378,341,719,129,...,400,822,425,401,0,0,0,18,808,0
66,JUNIN,HUARIPAMPA,P.HUARIPAMPA,21,34,55,73,78,151,45,...,112,196,94,112,0,0,0,206,0,0
72,JUNIN,MUQUIYAUYO,P.MUQUIYAUYO,58,63,121,252,211,463,172,...,272,564,310,274,0,0,0,361,131,92
74,JUNIN,ACOLLA,P.ACOLLA,45,38,83,160,117,277,66,...,155,346,205,155,0,0,0,333,27,0
90,JUNIN,MITO,A.ACO,39,23,62,136,52,188,118,...,75,250,175,75,0,0,0,214,36,0
96,JUNIN,CONCEPCIÓN,P.CONCEPCIÓN,38,43,81,178,164,342,82,...,201,397,216,207,0,0,0,141,282,0
97,JUNIN,CONCEPCIÓN,SANTA ROSA DE OCOPA,28,32,60,95,93,188,54,...,125,248,123,125,0,0,0,183,65,0
106,JUNIN,HUANCAYO,P.HUANCAYO,184,184,368,950,957,1907,317,...,1089,2164,1132,1141,2,0,308,1367,598,2
107,JUNIN,HUANCAYO,CAJAS,40,64,104,187,134,321,85,...,198,413,227,198,0,0,11,222,192,0
109,JUNIN,CHUPACA,P.CHUPACA,82,77,159,451,316,767,143,...,393,922,533,393,0,0,44,585,297,0
110,JUNIN,CHUPACA,A.ISCOS,31,30,61,154,119,273,40,...,149,329,185,149,0,0,0,280,54,0
117,JUNIN,CHUPACA,HUAMANCACA,27,27,54,73,71,144,17,...,98,198,100,98,0,0,0,153,45,0
119,JUNIN,CHUPACA,AHUAC,41,36,77,110,114,224,65,...,150,296,151,150,0,0,0,179,122,0
121,JUNIN,SAN GERÓNIMO,P.SAN GERÓNIMO,51,42,93,246,238,484,162,...,278,554,297,280,0,0,348,157,72,0
129,JUNIN,SAPALLANGA,P.SAPALLANGA,58,38,96,169,94,263,186,...,132,359,227,132,0,0,7,328,24,0
131,JUNIN,SAPALLANGA,P.PUCARÁ,45,45,90,161,117,278,182,...,162,368,206,162,0,0,6,330,32,0
135,JUNIN,CHONGOS,P.CHONGOS,46,50,96,250,235,485,133,...,284,580,296,285,0,0,23,306,252,0
141,JUNIN,CHONGOS,A.HUAMANCACA,32,28,60,90,73,163,49,...,101,223,122,101,0,0,0,53,170,0
153,JUNIN,HUAYUCACHI,P.HUAYUCACHI,40,32,72,110,74,184,36,...,106,256,150,106,0,0,1,240,15,0
161,JUNIN,TARMA,P.TARMA,107,117,224,386,427,813,258,...,502,963,490,543,3,1,158,189,689,1
167,JUNIN,JUNÍN,P.JUNÍN,69,73,142,284,191,475,32,...,264,614,353,264,0,0,8,542,67,0
168,JUNIN,JUNÍN,CACAS,81,79,160,194,172,366,92,...,251,526,271,251,0,0,0,526,0,0
169,JUNIN,JUNÍN,HUASAHUASY,56,44,100,135,137,272,22,...,181,372,191,181,0,0,2,0,370,0
175,JUNIN,ACOBAMBA,P.ACOBAMBA,44,41,85,197,163,360,77,...,204,445,241,204,0,0,69,261,115,0
177,JUNIN,ACOBAMBA,C.HUARACAYO,37,32,69,104,72,176,23,...,104,245,141,104,0,0,5,228,12,0
178,JUNIN,ACOBAMBA,A.PALCA,53,53,106,132,151,283,62,...,204,389,185,204,0,0,30,197,162,0

In [36]:
junin_50_70 = junin[(junin['4_6_years_total'] > 50) & (junin['6_14_years_total'] > 70)]
junin_50_70

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,209,544,361,216,1,1,4,284,290,1
28,JUNIN,CAYNA,PÁUCAR,26,31,57,66,44,110,18,...,75,147,72,0,0,0,0,119,28,0
47,JUNIN,JAUJA,P.JAUJA,69,71,140,375,327,702,265,...,374,749,444,398,0,0,63,117,662,0
51,JUNIN,JAUJA,A.HUERTAS,22,38,60,103,87,190,84,...,125,246,125,125,0,0,0,195,55,0
57,JUNIN,JAUJA,P.RICRÁN,36,21,57,98,93,191,42,...,114,248,134,114,0,0,0,240,8,0
59,JUNIN,APATA,P.APATA,133,82,215,487,218,705,85,...,299,908,620,300,0,0,2,264,654,0
62,JUNIN,APATA,PACUCHO,29,22,51,117,113,230,50,...,135,280,146,135,0,0,0,34,247,0
63,JUNIN,ORCOTUNA,P.ORCOTUNA,47,60,107,378,341,719,129,...,400,822,425,401,0,0,0,18,808,0
66,JUNIN,HUARIPAMPA,P.HUARIPAMPA,21,34,55,73,78,151,45,...,112,196,94,112,0,0,0,206,0,0
72,JUNIN,MUQUIYAUYO,P.MUQUIYAUYO,58,63,121,252,211,463,172,...,272,564,310,274,0,0,0,361,131,92
74,JUNIN,ACOLLA,P.ACOLLA,45,38,83,160,117,277,66,...,155,346,205,155,0,0,0,333,27,0
90,JUNIN,MITO,A.ACO,39,23,62,136,52,188,118,...,75,250,175,75,0,0,0,214,36,0
96,JUNIN,CONCEPCIÓN,P.CONCEPCIÓN,38,43,81,178,164,342,82,...,201,397,216,207,0,0,0,141,282,0
97,JUNIN,CONCEPCIÓN,SANTA ROSA DE OCOPA,28,32,60,95,93,188,54,...,125,248,123,125,0,0,0,183,65,0
106,JUNIN,HUANCAYO,P.HUANCAYO,184,184,368,950,957,1907,317,...,1089,2164,1132,1141,2,0,308,1367,598,2
107,JUNIN,HUANCAYO,CAJAS,40,64,104,187,134,321,85,...,198,413,227,198,0,0,11,222,192,0
109,JUNIN,CHUPACA,P.CHUPACA,82,77,159,451,316,767,143,...,393,922,533,393,0,0,44,585,297,0
110,JUNIN,CHUPACA,A.ISCOS,31,30,61,154,119,273,40,...,149,329,185,149,0,0,0,280,54,0
117,JUNIN,CHUPACA,HUAMANCACA,27,27,54,73,71,144,17,...,98,198,100,98,0,0,0,153,45,0
119,JUNIN,CHUPACA,AHUAC,41,36,77,110,114,224,65,...,150,296,151,150,0,0,0,179,122,0
121,JUNIN,SAN GERÓNIMO,P.SAN GERÓNIMO,51,42,93,246,238,484,162,...,278,554,297,280,0,0,348,157,72,0
129,JUNIN,SAPALLANGA,P.SAPALLANGA,58,38,96,169,94,263,186,...,132,359,227,132,0,0,7,328,24,0
131,JUNIN,SAPALLANGA,P.PUCARÁ,45,45,90,161,117,278,182,...,162,368,206,162,0,0,6,330,32,0
135,JUNIN,CHONGOS,P.CHONGOS,46,50,96,250,235,485,133,...,284,580,296,285,0,0,23,306,252,0
141,JUNIN,CHONGOS,A.HUAMANCACA,32,28,60,90,73,163,49,...,101,223,122,101,0,0,0,53,170,0
153,JUNIN,HUAYUCACHI,P.HUAYUCACHI,40,32,72,110,74,184,36,...,106,256,150,106,0,0,1,240,15,0
161,JUNIN,TARMA,P.TARMA,107,117,224,386,427,813,258,...,502,963,490,543,3,1,158,189,689,1
167,JUNIN,JUNÍN,P.JUNÍN,69,73,142,284,191,475,32,...,264,614,353,264,0,0,8,542,67,0
168,JUNIN,JUNÍN,CACAS,81,79,160,194,172,366,92,...,251,526,271,251,0,0,0,526,0,0
169,JUNIN,JUNÍN,HUASAHUASY,56,44,100,135,137,272,22,...,181,372,191,181,0,0,2,0,370,0
175,JUNIN,ACOBAMBA,P.ACOBAMBA,44,41,85,197,163,360,77,...,204,445,241,204,0,0,69,261,115,0
177,JUNIN,ACOBAMBA,C.HUARACAYO,37,32,69,104,72,176,23,...,104,245,141,104,0,0,5,228,12,0
178,JUNIN,ACOBAMBA,A.PALCA,53,53,106,132,151,283,62,...,204,389,185,204,0,0,30,197,162,0

In [30]:
junin.loc[:,'Region':'6_14_years_total']

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468
1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96
2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71
3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44
4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42
...,...,...,...,...,...,...,...,...,...
192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71
193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112
196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112

In [35]:
junin.loc[:,'instruction_men':'no_instruction_total']

,instruction_men,instruction_women,instruction_total,no_instruction_men,no_instruction_women,no_instruction_total
0,61,29,90,301,188,489
1,5,10,15,45,50,95
2,40,0,40,7,25,32
3,25,0,25,0,25,25
4,0,0,0,25,25,50
...,...,...,...,...,...,...
192,18,0,18,54,0,54
193,13,0,13,3,7,10
194,15,6,21,7,2,9
195,48,24,72,28,20,48
196,4,0,4,92,30,122

In [38]:
junin.columns

Index(['Region', 'District', 'Place', '4_6_years_men', '4_6_years_women',
       '4_6_years_total', '6_14_years_men', '6_14_years_women',
       '6_14_years_total', 'man_read', 'women_read', 'total_read',
       'men_not_read', 'women_not_read', 'total_not_read', 'man_write',
       'women_write', 'total_write', 'men_not_write', 'women_not_write',
       'total_not_write', 'instruction_men', 'instruction_women',
       'instruction_total', 'no_instruction_men', 'no_instruction_women',
       'no_instruction_total', 'finished_instr_men', 'finished_instr_women',
       'finished_instr_total', 'not_finished_instr_men',
       'not_finished_instr_women', 'not_finished_instr_total', 'peruvian_men',
       'peruvian_women', 'foreign_men', 'foreign_women', 'whites', 'natives',
       'mestizos', 'blacks'],
      dtype='object')

### Sorting and Subsetting

In [39]:
junin.sort_values('District')

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
178,JUNIN,ACOBAMBA,A.PALCA,53,53,106,132,151,283,62,...,204,389,185,204,0,0,30,197,162,0
175,JUNIN,ACOBAMBA,P.ACOBAMBA,44,41,85,197,163,360,77,...,204,445,241,204,0,0,69,261,115,0
176,JUNIN,ACOBAMBA,PICOY,12,8,20,40,32,72,23,...,40,92,52,40,0,0,4,72,16,0
177,JUNIN,ACOBAMBA,C.HUARACAYO,37,32,69,104,72,176,23,...,104,245,141,104,0,0,5,228,12,0
179,JUNIN,ACOBAMBA,C.HUAILAHUICHÁN,23,18,41,55,52,107,28,...,70,148,78,70,0,0,70,78,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,JUNIN,YANAHUANCA,HUARANTAMBO,5,1,6,20,24,44,0,...,25,50,25,25,0,0,30,20,0,0
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,41,...,37,103,76,44,0,0,37,14,69,0
193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,8,...,7,23,16,7,0,0,0,21,2,0
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,7,...,8,30,22,8,0,0,0,4,26,0
196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,8,...,30,126,96,30,0,0,1,118,7,0

In [41]:
junin.sort_values('District', ascending = False)

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,8,...,30,126,96,30,0,0,1,118,7,0
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,41,...,37,103,76,44,0,0,37,14,69,0
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,7,...,8,30,22,8,0,0,0,4,26,0
193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,8,...,7,23,16,7,0,0,0,21,2,0
40,JUNIN,YANAHUANCA,ROCO,4,4,8,21,21,42,0,...,25,50,25,25,0,0,0,50,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,JUNIN,ACOBAMBA,C.HUAILAHUICHÁN,23,18,41,55,52,107,28,...,70,148,78,70,0,0,70,78,0,0
178,JUNIN,ACOBAMBA,A.PALCA,53,53,106,132,151,283,62,...,204,389,185,204,0,0,30,197,162,0
177,JUNIN,ACOBAMBA,C.HUARACAYO,37,32,69,104,72,176,23,...,104,245,141,104,0,0,5,228,12,0
176,JUNIN,ACOBAMBA,PICOY,12,8,20,40,32,72,23,...,40,92,52,40,0,0,4,72,16,0
175,JUNIN,ACOBAMBA,P.ACOBAMBA,44,41,85,197,163,360,77,...,204,445,241,204,0,0,69,261,115,0

In [40]:
junin.sort_values('Place')

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
24,JUNIN,CAYNA,A. COLPAS,0,0,0,26,0,26,0,...,0,26,26,0,0,0,0,26,0,0
90,JUNIN,MITO,A.ACO,39,23,62,136,52,188,118,...,75,250,175,75,0,0,0,214,36,0
99,JUNIN,CONCEPCIÓN,A.ALAYO,3,8,11,22,29,51,13,...,37,62,25,37,0,0,0,62,0,0
146,JUNIN,COLCA,A.CHACAPAMPA,27,17,44,69,55,124,2,...,72,168,96,72,0,0,24,144,0,0
87,JUNIN,MITO,A.CHAMBARÁ,19,12,31,57,38,95,54,...,50,124,43,50,0,0,0,74,52,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,JUNIN,YANAHUANCA,YACÁN,9,12,21,41,38,79,0,...,50,100,50,50,0,0,0,75,25,0
114,JUNIN,CHUPACA,YANACANCHA,15,6,21,76,37,113,18,...,43,134,91,43,0,0,0,123,11,0
171,JUNIN,JUNÍN,YANEC,12,16,28,49,29,78,0,...,45,106,61,45,0,0,0,106,0,0
79,JUNIN,ACOLLA,YAUJAILLO,11,2,13,13,4,17,3,...,6,30,24,6,0,0,0,30,0,0
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,41,...,37,103,76,44,0,0,37,14,69,0

In [44]:
junin.sort_values(['District','Place'], ascending = False)

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,41,...,37,103,76,44,0,0,37,14,69,0
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,7,...,8,30,22,8,0,0,0,4,26,0
193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,8,...,7,23,16,7,0,0,0,21,2,0
196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,8,...,30,126,96,30,0,0,1,118,7,0
43,JUNIN,YANAHUANCA,YACÁN,9,12,21,41,38,79,0,...,50,100,50,50,0,0,0,75,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,JUNIN,ACOBAMBA,P.PALCAMAYO,18,25,43,82,75,157,29,...,100,200,100,100,0,0,0,156,44,0
175,JUNIN,ACOBAMBA,P.ACOBAMBA,44,41,85,197,163,360,77,...,204,445,241,204,0,0,69,261,115,0
177,JUNIN,ACOBAMBA,C.HUARACAYO,37,32,69,104,72,176,23,...,104,245,141,104,0,0,5,228,12,0
179,JUNIN,ACOBAMBA,C.HUAILAHUICHÁN,23,18,41,55,52,107,28,...,70,148,78,70,0,0,70,78,0,0
178,JUNIN,ACOBAMBA,A.PALCA,53,53,106,132,151,283,62,...,204,389,185,204,0,0,30,197,162,0

In [45]:
junin.loc[junin['Place'].str.contains('PACHA')]

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
49,JUNIN,JAUJA,C.PACAPACHA,1,7,8,24,18,42,17,...,25,50,25,25,0,0,0,50,0,0
140,JUNIN,CHONGOS,CARHUAPACHA,2,1,3,18,17,35,1,...,18,38,20,18,0,0,0,33,5,0
160,JUNIN,HUAYUCACHI,PACHA,18,9,27,31,12,43,10,...,21,70,49,21,0,0,0,70,0,0
183,JUNIN,OROYA,PACHA,2,4,6,7,3,10,0,...,7,16,9,7,0,0,0,16,0,0
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,7,...,8,30,22,8,0,0,0,4,26,0

In [46]:
junin.loc[junin['Place'].str.contains('HUA')]

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
11,JUNIN,CIUDAD DEL CERRO,H.PARIAHUANCA,2,6,8,10,12,22,0,...,18,30,12,18,0,0,0,24,6,0
14,JUNIN,HUAYLLAY,P.HUALLAY,5,11,16,55,37,92,9,...,48,108,60,48,0,0,0,92,16,0
15,JUNIN,HUAYLLAY,C.HUAYCHAO,1,0,1,24,8,32,7,...,8,33,25,8,0,0,0,33,0,0
35,JUNIN,YANAHUANCA,P.YANAHUANCA,6,18,24,75,82,157,23,...,100,181,81,100,0,0,15,116,47,3
36,JUNIN,YANAHUANCA,HUAYLACIRCA,4,4,8,21,21,42,0,...,25,50,25,25,0,0,0,50,0,0
37,JUNIN,YANAHUANCA,HUARANTAMBO,5,1,6,20,24,44,0,...,25,50,25,25,0,0,30,20,0,0
50,JUNIN,JAUJA,HUANCAS,3,2,5,29,40,69,13,...,42,74,32,42,0,0,0,74,0,0
55,JUNIN,JAUJA,HUALÁ,9,9,18,57,28,85,39,...,37,103,66,37,0,0,0,99,4,0
60,JUNIN,APATA,HUAMALÍ,17,26,43,58,49,107,22,...,75,149,75,75,0,0,6,85,59,0
66,JUNIN,HUARIPAMPA,P.HUARIPAMPA,21,34,55,73,78,151,45,...,112,196,94,112,0,0,0,206,0,0
83,JUNIN,CINCOS,P.HUANCARÍ,5,12,17,81,79,160,31,...,91,177,86,91,0,0,0,55,122,0
84,JUNIN,CINCOS,C.CHALHUAS,5,4,9,18,20,38,2,...,24,47,23,24,0,0,0,47,0,0
89,JUNIN,MITO,HUACHAC,19,15,34,61,47,108,53,...,62,140,80,62,0,0,0,115,27,0
98,JUNIN,CONCEPCIÓN,HUANTAR,3,0,3,47,41,88,34,...,41,91,50,41,0,0,0,90,1,0
105,JUNIN,MATAHUASI,P.MATAHUASI,10,18,28,90,82,172,49,...,100,196,100,100,0,0,0,200,0,0
106,JUNIN,HUANCAYO,P.HUANCAYO,184,184,368,950,957,1907,317,...,1089,2164,1132,1141,2,0,308,1367,598,2
112,JUNIN,CHUPACA,HUAUSCA GRANDE,12,23,35,63,47,110,29,...,70,145,75,70,0,0,0,44,101,0
116,JUNIN,CHUPACA,HUAYAN,10,8,18,64,41,105,24,...,49,123,74,49,0,0,0,61,62,0
117,JUNIN,CHUPACA,HUAMANCACA,27,27,54,73,71,144,17,...,98,198,100,98,0,0,0,153,45,0
119,JUNIN,CHUPACA,AHUAC,41,36,77,110,114,224,65,...,150,296,151,150,0,0,0,179,122,0
122,JUNIN,SAN GERÓNIMO,HUALHUAS,20,20,40,92,90,182,40,...,110,222,112,110,0,0,222,0,0,0
124,JUNIN,SAN GERÓNIMO,QUICHUAY,13,19,32,62,56,118,31,...,75,149,75,75,0,0,59,26,65,0
140,JUNIN,CHONGOS,CARHUAPACHA,2,1,3,18,17,35,1,...,18,38,20,18,0,0,0,33,5,0
141,JUNIN,CHONGOS,A.HUAMANCACA,32,28,60,90,73,163,49,...,101,223,122,101,0,0,0,53,170,0
143,JUNIN,SICAYA,A.HUANCHAC,7,17,24,72,53,125,79,...,70,149,79,70,0,0,0,44,105,0
147,JUNIN,COLCA,HUASICANCHA,10,4,14,15,10,25,0,...,14,39,25,14,0,0,0,39,0,0
153,JUNIN,HUAYUCACHI,P.HUAYUCACHI,40,32,72,110,74,184,36,...,106,256,150,106,0,0,1,240,15,0
154,JUNIN,HUAYUCACHI,HUAMANMARCA,9,10,19,42,23,65,11,...,33,84,51,33,0,0,0,84,0,0
157,JUNIN,HUAYUCACHI,HUARAPUQUIO,12,29,41,51,49,100,26,...,78,141,63,78,0,0,0,141,0,0
158,JUNIN,HUAYUCACHI,CULLHUAS,5,5,10,39,26,65,44,...,31,75,44,31,0,0,0,75,0,0
169,JUNIN,JUNÍN,HUASAHUASY,56,44,100,135,137,272,22,...,181,372,191,181,0,0,2,0,370,0
177,JUNIN,ACOBAMBA,C.HUARACAYO,37,32,69,104,72,176,23,...,104,245,141,104,0,0,5,228,12,0
179,JUNIN,ACOBAMBA,C.HUAILAHUICHÁN,23,18,41,55,52,107,28,...,70,148,78,70,0,0,70,78,0,0
182,JUNIN,OROYA,HUAYNACANCHA,4,2,6,11,16,27,0,...,18,33,15,18,0,0,0,33,0,0
184,JUNIN,OROYA,HUAYHUAY,13,8,21,55,33,88,47,...,41,105,68,41,0,0,0,108,1,0
185,JUNIN,CARHUAMAYO,P.CARHUAMAYO,35,6,41,110,32,142,25,...,38,183,145,38,0,0,3,143,35,0

In [48]:
junin.loc[junin['District'].str.contains('AC')]

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
17,JUNIN,CHACAYÁN,P.CHACAYÁN,0,5,5,171,151,322,28,...,156,327,171,156,0,0,12,284,31,0
18,JUNIN,CHACAYÁN,VILCABAMBA,23,16,39,78,84,162,0,...,100,201,101,100,0,0,0,201,0,0
19,JUNIN,CHACAYÁN,CUCHES,17,3,20,48,42,90,0,...,45,110,65,45,0,0,0,110,0,0
20,JUNIN,CHACAYÁN,CHANGO,12,3,15,142,94,236,0,...,97,251,154,97,0,0,0,251,0,0
21,JUNIN,CHACAYÁN,MITO,4,1,5,55,36,91,0,...,37,96,59,37,0,0,0,96,0,0
22,JUNIN,CHACAYÁN,ANTAPIRCA,20,15,35,29,60,89,0,...,75,124,49,75,0,0,0,124,0,0
46,JUNIN,NINACACA,P.OXAPAMPA,3,0,3,18,11,29,3,...,11,32,21,11,0,0,24,0,8,0
74,JUNIN,ACOLLA,P.ACOLLA,45,38,83,160,117,277,66,...,155,346,205,155,0,0,0,333,27,0
75,JUNIN,ACOLLA,MARCO,16,12,28,94,55,149,34,...,67,177,110,67,0,0,0,167,10,0
76,JUNIN,ACOLLA,TRAGADERO,20,13,33,87,52,139,67,...,65,168,107,65,0,0,0,169,3,0
77,JUNIN,ACOLLA,CHOCÓN,2,0,2,16,22,38,2,...,22,40,18,22,0,0,0,40,0,0
78,JUNIN,ACOLLA,ACAYA,2,2,4,29,21,50,7,...,23,54,31,23,0,0,0,54,0,0
79,JUNIN,ACOLLA,YAUJAILLO,11,2,13,13,4,17,3,...,6,30,24,6,0,0,0,30,0,0
80,JUNIN,ACOLLA,CURICACA,8,3,11,25,10,35,18,...,13,46,33,13,0,0,0,46,0,0
109,JUNIN,CHUPACA,P.CHUPACA,82,77,159,451,316,767,143,...,393,922,533,393,0,0,44,585,297,0
110,JUNIN,CHUPACA,A.ISCOS,31,30,61,154,119,273,40,...,149,329,185,149,0,0,0,280,54,0
111,JUNIN,CHUPACA,ANTAPAMPA,9,7,16,16,18,34,0,...,25,50,25,25,0,0,0,50,0,0
112,JUNIN,CHUPACA,HUAUSCA GRANDE,12,23,35,63,47,110,29,...,70,145,75,70,0,0,0,44,101,0
113,JUNIN,CHUPACA,SAN JUAN DE TARPA,13,18,31,59,32,91,52,...,50,122,72,50,0,0,0,54,68,0
114,JUNIN,CHUPACA,YANACANCHA,15,6,21,76,37,113,18,...,43,134,91,43,0,0,0,123,11,0
115,JUNIN,CHUPACA,COPCA,5,12,17,61,57,118,0,...,69,135,66,69,0,0,0,132,3,0
116,JUNIN,CHUPACA,HUAYAN,10,8,18,64,41,105,24,...,49,123,74,49,0,0,0,61,62,0
117,JUNIN,CHUPACA,HUAMANCACA,27,27,54,73,71,144,17,...,98,198,100,98,0,0,0,153,45,0
118,JUNIN,CHUPACA,PILCOMAYO,14,10,24,86,90,176,38,...,100,194,100,100,0,0,0,132,68,0
119,JUNIN,CHUPACA,AHUAC,41,36,77,110,114,224,65,...,150,296,151,150,0,0,0,179,122,0
120,JUNIN,CHUPACA,ACAC,22,12,34,45,43,88,23,...,55,122,67,55,0,0,14,108,0,0
153,JUNIN,HUAYUCACHI,P.HUAYUCACHI,40,32,72,110,74,184,36,...,106,256,150,106,0,0,1,240,15,0
154,JUNIN,HUAYUCACHI,HUAMANMARCA,9,10,19,42,23,65,11,...,33,84,51,33,0,0,0,84,0,0
155,JUNIN,HUAYUCACHI,VIQUES,12,19,31,88,71,159,36,...,90,190,100,90,0,0,0,190,0,0
156,JUNIN,HUAYUCACHI,CACAS,19,11,30,31,39,70,5,...,50,100,50,50,0,0,0,100,0,0
157,JUNIN,HUAYUCACHI,HUARAPUQUIO,12,29,41,51,49,100,26,...,78,141,63,78,0,0,0,141,0,0
158,JUNIN,HUAYUCACHI,CULLHUAS,5,5,10,39,26,65,44,...,31,75,44,31,0,0,0,75,0,0
159,JUNIN,HUAYUCACHI,RETAMA,12,12,24,38,21,59,23,...,33,83,50,33,0,0,0,83,0,0
160,JUNIN,HUAYUCACHI,PACHA,18,9,27,31,12,43,10,...,21,70,49,21,0,0,0,70,0,0
175,JUNIN,ACOBAMBA,P.ACOBAMBA,44,41,85,197,163,360,77,...,204,445,241,204,0,0,69,261,115,0
176,JUNIN,ACOBAMBA,PICOY,12,8,20,40,32,72,23,...,40,92,52,40,0,0,4,72,16,0
177,JUNIN,ACOBAMBA,C.HUARACAYO,37,32,69,104,72,176,23,...,104,245,141,104,0,0,5,228,12,0
178,JUNIN,ACOBAMBA,A.PALCA,53,53,106,132,151,283,62,...,204,389,185,204,0,0,30,197,162,0
179,JUNIN,ACOBAMBA,C.HUAILAHUICHÁN,23,18,41,55,52,107,28,...,70,148,78,70,0,0,70,78,0,0
180,JUNIN,ACOBAMBA,P.PALCAMAYO,18,25,43,82,75,157,29,...,100,200,100,100,0,0,0,156,44,0
191,JUNIN,CHACAPALCA,SUITUCANCHA,0,4,4,25,33,58,25,...,37,62,25,37,0,0,0,33,29,0
192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,42,...,0,72,72,0,0,0,0,35,39,0

In [51]:
junin['4_6_years_total'].idxmax()

106

In [52]:
junin.iloc[106]

Region                           JUNIN
District                      HUANCAYO
Place                       P.HUANCAYO
4_6_years_men                      184
4_6_years_women                    184
4_6_years_total                    368
6_14_years_men                     950
6_14_years_women                   957
6_14_years_total                  1907
man_read                           317
women_read                         225
total_read                         542
men_not_read                       817
women_not_read                     916
total_not_read                    1733
man_write                          198
women_write                        153
total_write                        351
men_not_write                      936
women_not_write                    988
total_not_write                   1924
instruction_men                    235
instruction_women                  178
instruction_total                  413
no_instruction_men                 899
no_instruction_women               963
no_instruction_total              1862
finished_instr_men                  59
finished_instr_women                52
finished_instr_total               111
not_finished_instr_men            1075
not_finished_instr_women          1089
not_finished_instr_total          2164
peruvian_men                      1132
peruvian_women                    1141
foreign_men                          2
foreign_women                        0
whites                             308
natives                           1367
mestizos                           598
blacks                               2
Name: 106, dtype: object

In [53]:
junin['4_6_years_total'].idxmin()

24

In [54]:
junin.iloc[24]

Region                          JUNIN
District                        CAYNA
Place                       A. COLPAS
4_6_years_men                       0
4_6_years_women                     0
4_6_years_total                     0
6_14_years_men                     26
6_14_years_women                    0
6_14_years_total                   26
man_read                            0
women_read                          0
total_read                          0
men_not_read                       26
women_not_read                      0
total_not_read                     26
man_write                           0
women_write                         0
total_write                         0
men_not_write                      26
women_not_write                     0
total_not_write                    26
instruction_men                     0
instruction_women                   0
instruction_total                   0
no_instruction_men                 26
no_instruction_women                0
no_instruction_total               26
finished_instr_men                  0
finished_instr_women                0
finished_instr_total                0
not_finished_instr_men             26
not_finished_instr_women            0
not_finished_instr_total           26
peruvian_men                       26
peruvian_women                      0
foreign_men                         0
foreign_women                       0
whites                              0
natives                            26
mestizos                            0
blacks                              0
Name: 24, dtype: object

In [56]:
junin['whites'].idxmax()

121

In [58]:
junin.iloc[121]

Region                               JUNIN
District                      SAN GERÓNIMO
Place                       P.SAN GERÓNIMO
4_6_years_men                           51
4_6_years_women                         42
4_6_years_total                         93
6_14_years_men                         246
6_14_years_women                       238
6_14_years_total                       484
man_read                               162
women_read                              72
total_read                             234
men_not_read                           135
women_not_read                         208
total_not_read                         343
man_write                              118
women_write                             31
total_write                            149
men_not_write                          179
women_not_write                        249
total_not_write                        428
instruction_men                          0
instruction_women                        0
instruction_total                        0
no_instruction_men                     297
no_instruction_women                   280
no_instruction_total                   577
finished_instr_men                      21
finished_instr_women                     2
finished_instr_total                    23
not_finished_instr_men                 276
not_finished_instr_women               278
not_finished_instr_total               554
peruvian_men                           297
peruvian_women                         280
foreign_men                              0
foreign_women                            0
whites                                 348
natives                                157
mestizos                                72
blacks                                   0
Name: 121, dtype: object

In [55]:
junin['4_6_years_total'].mode()

0    8
dtype: int64

In [59]:
junin['blacks'].idxmax()

72

In [60]:
junin.iloc[72]

Region                             JUNIN
District                      MUQUIYAUYO
Place                       P.MUQUIYAUYO
4_6_years_men                         58
4_6_years_women                       63
4_6_years_total                      121
6_14_years_men                       252
6_14_years_women                     211
6_14_years_total                     463
man_read                             172
women_read                            60
total_read                           232
men_not_read                         138
women_not_read                       214
total_not_read                       352
man_write                            134
women_write                            0
total_write                          134
men_not_write                        176
women_not_write                      233
total_not_write                      409
instruction_men                      157
instruction_women                     41
instruction_total                    198
no_instruction_men                   153
no_instruction_women                 233
no_instruction_total                 386
finished_instr_men                    18
finished_instr_women                   2
finished_instr_total                  20
not_finished_instr_men               292
not_finished_instr_women             272
not_finished_instr_total             564
peruvian_men                         310
peruvian_women                       274
foreign_men                            0
foreign_women                          0
whites                                 0
natives                              361
mestizos                             131
blacks                                92
Name: 72, dtype: object

In [61]:
junin_hua = junin.loc[junin['District'] == 'HUANCAYO']
junin_hua

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
106,JUNIN,HUANCAYO,P.HUANCAYO,184,184,368,950,957,1907,317,...,1089,2164,1132,1141,2,0,308,1367,598,2
107,JUNIN,HUANCAYO,CAJAS,40,64,104,187,134,321,85,...,198,413,227,198,0,0,11,222,192,0
108,JUNIN,HUANCAYO,PACCHA,18,24,42,89,71,160,53,...,94,200,107,95,0,0,8,58,136,0

In [ ]:
# df["edad"] = pd.to_numeric(df["edad"], downcast="float")

### Filtering Data

### .isin()

### Data Manipulation